### PR TITLE
User login & Sign Up

### PR DESCRIPTION
**Pull request by arshsharma96**

### CODE REVIEW

**Comment by NIVIDSHAH208** [comment]
An issue with Sign Up feature. Fix that and resolve in issues.

**Comment by arshsharma96** [comment]
I am still fixing things in this, so please keep the request open.

**Comment by singha163** [comment]
image

**Comment by arshsharma96** [comment]
I checked again and able to add and login from my device. Can you please recheck your connection with firebase @singha163 @NIVIDSHAH208

**Pull request merged**
